// provided.js - generated by ephemient/aoc2023/Kotlin benchmarks, 2023-12-09 06:12:25.456690306

var providedBenchmarks = ["js","jvm","linuxX64"];

var providedBenchmarkStore = {
  "js": [
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day1Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 435.50074864769084,
        "scoreError": 3.162610761438833,
        "scoreConfidence": [
          432.338137886252,
          438.66335940912967
        ],
        "scorePercentiles": {
          "0.00": 431.7404833388091,
          "25.00": 431.94716609952826,
          "50.00": 435.4105901436544,
          "75.00": 439.0994104478716,
          "90.00": 439.7406647019547,
          "99.00": 439.7406647019547,
          "99.90": 439.7406647019547,
          "99.99": 439.7406647019547,
          "100.00": 439.7406647019547
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            435.4105901436544,
            431.7404833388091,
            438.4581561937885,
            432.1538488602474,
            439.7406647019547
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day1Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 332.04869877320664,
        "scoreError": 2.956090770740233,
        "scoreConfidence": [
          329.0926080024664,
          335.00478954394686
        ],
        "scorePercentiles": {
          "0.00": 328.5588234309703,
          "25.00": 328.56212593002425,
          "50.00": 332.5611007997433,
          "75.00": 335.27907060312066,
          "90.00": 335.43457013225236,
          "99.00": 335.43457013225236,
          "99.90": 335.43457013225236,
          "99.99": 335.43457013225236,
          "100.00": 335.43457013225236
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            328.5654284290782,
            328.5588234309703,
            332.5611007997433,
            335.12357107398896,
            335.43457013225236
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day2Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 791.385250650091,
        "scoreError": 7.045694383894205,
        "scoreConfidence": [
          784.3395562661968,
          798.4309450339853
        ],
        "scorePercentiles": {
          "0.00": 779.4750830783319,
          "25.00": 783.026217041229,
          "50.00": 796.6069600568645,
          "75.00": 797.1334295555664,
          "90.00": 797.3844718210801,
          "99.00": 797.3844718210801,
          "99.90": 797.3844718210801,
          "99.99": 797.3844718210801,
          "100.00": 797.3844718210801
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            779.4750830783319,
            796.6069600568645,
            786.5773510041261,
            797.3844718210801,
            796.8823872900526
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day2Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 800.7794806573286,
        "scoreError": 2.5483825573928414,
        "scoreConfidence": [
          798.2310980999357,
          803.3278632147214
        ],
        "scorePercentiles": {
          "0.00": 797.9867240249147,
          "25.00": 798.6774596358714,
          "50.00": 800.1823558007509,
          "75.00": 803.1800641070744,
          "90.00": 805.6434737596962,
          "99.00": 805.6434737596962,
          "99.90": 805.6434737596962,
          "99.99": 805.6434737596962,
          "100.00": 805.6434737596962
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            800.1823558007509,
            799.3681952468282,
            805.6434737596962,
            800.7166544544525,
            797.9867240249147
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day3Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 421.70733572086846,
        "scoreError": 2.143425782082354,
        "scoreConfidence": [
          419.5639099387861,
          423.85076150295083
        ],
        "scorePercentiles": {
          "0.00": 418.70532503675184,
          "25.00": 419.33929430495533,
          "50.00": 421.75330131094427,
          "75.00": 424.0523943417437,
          "90.00": 424.7227516058205,
          "99.00": 424.7227516058205,
          "99.90": 424.7227516058205,
          "99.99": 424.7227516058205,
          "100.00": 424.7227516058205
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            421.75330131094427,
            418.70532503675184,
            419.9732635731588,
            424.7227516058205,
            423.3820370776669
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day3Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 424.61481977692586,
        "scoreError": 0.5713756267221196,
        "scoreConfidence": [
          424.04344415020375,
          425.18619540364796
        ],
        "scorePercentiles": {
          "0.00": 423.90956978327426,
          "25.00": 424.1298640968183,
          "50.00": 424.4717572078358,
          "75.00": 425.1713067415784,
          "90.00": 425.6674979216809,
          "99.00": 425.6674979216809,
          "99.90": 425.6674979216809,
          "99.99": 425.6674979216809,
          "100.00": 425.6674979216809
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            423.90956978327426,
            424.4717572078358,
            424.35015841036244,
            424.67511556147593,
            425.6674979216809
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day4Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 280.6299127744486,
        "scoreError": 1.612008162346448,
        "scoreConfidence": [
          279.01790461210214,
          282.24192093679505
        ],
        "scorePercentiles": {
          "0.00": 278.51770155075684,
          "25.00": 278.75734177140146,
          "50.00": 281.06362927101867,
          "75.00": 282.2856255292108,
          "90.00": 282.8896970637694,
          "99.00": 282.8896970637694,
          "99.90": 282.8896970637694,
          "99.99": 282.8896970637694,
          "100.00": 282.8896970637694
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            278.99698199204613,
            278.51770155075684,
            281.06362927101867,
            281.6815539946522,
            282.8896970637694
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day4Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 281.630922943332,
        "scoreError": 0.6277198783262631,
        "scoreConfidence": [
          281.0032030650057,
          282.25864282165827
        ],
        "scorePercentiles": {
          "0.00": 280.66263873796385,
          "25.00": 281.04654954528206,
          "50.00": 281.4506661512108,
          "75.00": 282.30542473744254,
          "90.00": 282.5615878950009,
          "99.00": 282.5615878950009,
          "99.90": 282.5615878950009,
          "99.99": 282.5615878950009,
          "100.00": 282.5615878950009
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            281.4506661512108,
            280.66263873796385,
            282.5615878950009,
            282.0492615798842,
            281.4304603526003
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day5Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 302.6218841530219,
        "scoreError": 1.851296549342565,
        "scoreConfidence": [
          300.7705876036793,
          304.47318070236446
        ],
        "scorePercentiles": {
          "0.00": 301.089132456007,
          "25.00": 301.3831395146193,
          "50.00": 301.91944029437,
          "75.00": 304.2118507207504,
          "90.00": 306.3392680459624,
          "99.00": 306.3392680459624,
          "99.90": 306.3392680459624,
          "99.99": 306.3392680459624,
          "100.00": 306.3392680459624
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            306.3392680459624,
            301.089132456007,
            301.6771465732316,
            301.91944029437,
            302.08443339553844
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day5Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 209.31901550344097,
        "scoreError": 1.0272275047073829,
        "scoreConfidence": [
          208.29178799873358,
          210.34624300814835
        ],
        "scorePercentiles": {
          "0.00": 207.54690332057723,
          "25.00": 208.13673275135176,
          "50.00": 209.80368929307377,
          "75.00": 210.25896136071376,
          "90.00": 210.2698631326554,
          "99.00": 210.2698631326554,
          "99.90": 210.2698631326554,
          "99.99": 210.2698631326554,
          "100.00": 210.2698631326554
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            209.80368929307377,
            210.24805958877212,
            207.54690332057723,
            210.2698631326554,
            208.7265621821263
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day6Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 65256.36273500878,
        "scoreError": 869.159532488413,
        "scoreConfidence": [
          64387.203202520366,
          66125.52226749719
        ],
        "scorePercentiles": {
          "0.00": 63552.742064684244,
          "25.00": 64464.16625551095,
          "50.00": 65504.82694931631,
          "75.00": 65924.32710735282,
          "90.00": 66100.83463171466,
          "99.00": 66100.83463171466,
          "99.90": 66100.83463171466,
          "99.99": 66100.83463171466,
          "100.00": 66100.83463171466
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            65375.59044633766,
            63552.742064684244,
            66100.83463171466,
            65747.81958299098,
            65504.82694931631
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day6Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 100779.78501358179,
        "scoreError": 848.7904413474706,
        "scoreConfidence": [
          99930.99457223431,
          101628.57545492926
        ],
        "scorePercentiles": {
          "0.00": 99775.08861526551,
          "25.00": 99808.55823804034,
          "50.00": 100904.82930888273,
          "75.00": 101688.48964147276,
          "90.00": 102000.60211859041,
          "99.00": 102000.60211859041,
          "99.90": 102000.60211859041,
          "99.99": 102000.60211859041,
          "100.00": 102000.60211859041
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            99842.02786081517,
            99775.08861526551,
            101376.37716435512,
            100904.82930888273,
            102000.60211859041
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day7Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 45.2886956641611,
        "scoreError": 0.308628934283875,
        "scoreConfidence": [
          44.98006672987722,
          45.59732459844497
        ],
        "scorePercentiles": {
          "0.00": 44.83390623495718,
          "25.00": 44.94240542667568,
          "50.00": 45.330198091861966,
          "75.00": 45.61423468779606,
          "90.00": 45.71130381545963,
          "99.00": 45.71130381545963,
          "99.90": 45.71130381545963,
          "99.99": 45.71130381545963,
          "100.00": 45.71130381545963
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            44.83390623495718,
            45.5171655601325,
            45.05090461839417,
            45.71130381545963,
            45.330198091861966
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day7Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 47.19124814510728,
        "scoreError": 0.16680682500364052,
        "scoreConfidence": [
          47.02444132010364,
          47.35805497011092
        ],
        "scorePercentiles": {
          "0.00": 46.88793498011765,
          "25.00": 47.01700622421234,
          "50.00": 47.26471451074089,
          "75.00": 47.328756883185434,
          "90.00": 47.3904217909358,
          "99.00": 47.3904217909358,
          "99.90": 47.3904217909358,
          "99.99": 47.3904217909358,
          "100.00": 47.3904217909358
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            47.146077468307034,
            47.26471451074089,
            47.26709197543508,
            47.3904217909358,
            46.88793498011765
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day8Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 983.7739810897405,
        "scoreError": 5.746236191286143,
        "scoreConfidence": [
          978.0277448984543,
          989.5202172810266
        ],
        "scorePercentiles": {
          "0.00": 974.4386298796227,
          "25.00": 977.6942351863913,
          "50.00": 983.7501105430985,
          "75.00": 989.8656622664107,
          "90.00": 990.9973093934037,
          "99.00": 990.9973093934037,
          "99.90": 990.9973093934037,
          "99.99": 990.9973093934037,
          "100.00": 990.9973093934037
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            980.94984049316,
            983.7501105430985,
            974.4386298796227,
            990.9973093934037,
            988.7340151394176
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day8Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 196.4109901209785,
        "scoreError": 1.4089616510411964,
        "scoreConfidence": [
          195.0020284699373,
          197.81995177201972
        ],
        "scorePercentiles": {
          "0.00": 193.6703328729393,
          "25.00": 195.02191797510315,
          "50.00": 196.9318072176534,
          "75.00": 197.53965371851638,
          "90.00": 197.58157714728054,
          "99.00": 197.58157714728054,
          "99.90": 197.58157714728054,
          "99.99": 197.58157714728054,
          "100.00": 197.58157714728054
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            193.6703328729393,
            196.373503077267,
            197.49773028975218,
            197.58157714728054,
            196.9318072176534
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day9Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 349.1898901335294,
        "scoreError": 1.9843645992870245,
        "scoreConfidence": [
          347.2055255342424,
          351.1742547328164
        ],
        "scorePercentiles": {
          "0.00": 346.5419367724785,
          "25.00": 346.739229643602,
          "50.00": 350.56194267740784,
          "75.00": 350.9545243515175,
          "90.00": 351.34221534771495,
          "99.00": 351.34221534771495,
          "99.90": 351.34221534771495,
          "99.99": 351.34221534771495,
          "100.00": 351.34221534771495
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            351.34221534771495,
            350.56194267740784,
            346.9365225147256,
            350.56683335532,
            346.5419367724785
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day9Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 338.6201103948528,
        "scoreError": 1.6191663878796738,
        "scoreConfidence": [
          337.00094400697316,
          340.2392767827325
        ],
        "scorePercentiles": {
          "0.00": 337.1026622848331,
          "25.00": 337.11422106700996,
          "50.00": 337.62753569188027,
          "75.00": 340.62228707418194,
          "90.00": 340.8575521735281,
          "99.00": 340.8575521735281,
          "99.90": 340.8575521735281,
          "99.99": 340.8575521735281,
          "100.00": 340.8575521735281
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            337.1026622848331,
            337.62753569188027,
            340.8575521735281,
            337.1257798491868,
            340.3870219748357
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "jvm": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day1Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1546.54533854055,
        "scoreError": 40.50906335164196,
        "scoreConfidence": [
          1506.036275188908,
          1587.054401892192
        ],
        "scorePercentiles": {
          "0.0": 1531.450916794955,
          "50.0": 1547.5461016332988,
          "90.0": 1560.015826575425,
          "95.0": 1560.015826575425,
          "99.0": 1560.015826575425,
          "99.9": 1560.015826575425,
          "99.99": 1560.015826575425,
          "99.999": 1560.015826575425,
          "99.9999": 1560.015826575425,
          "100.0": 1560.015826575425
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1531.450916794955,
            1547.5461016332988,
            1542.8446546659552,
            1550.8691930331152,
            1560.015826575425
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day1Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1103.7414220730386,
        "scoreError": 70.2255489697181,
        "scoreConfidence": [
          1033.5158731033205,
          1173.9669710427568
        ],
        "scorePercentiles": {
          "0.0": 1072.3527804070325,
          "50.0": 1109.6482348516627,
          "90.0": 1117.752028947882,
          "95.0": 1117.752028947882,
          "99.0": 1117.752028947882,
          "99.9": 1117.752028947882,
          "99.99": 1117.752028947882,
          "99.999": 1117.752028947882,
          "99.9999": 1117.752028947882,
          "100.0": 1117.752028947882
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1114.3849453178254,
            1072.3527804070325,
            1104.5691208407895,
            1117.752028947882,
            1109.6482348516627
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day2Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2201.6076100647365,
        "scoreError": 50.80970717667981,
        "scoreConfidence": [
          2150.797902888057,
          2252.417317241416
        ],
        "scorePercentiles": {
          "0.0": 2179.8474884746734,
          "50.0": 2202.3414536561863,
          "90.0": 2214.014893999049,
          "95.0": 2214.014893999049,
          "99.0": 2214.014893999049,
          "99.9": 2214.014893999049,
          "99.99": 2214.014893999049,
          "99.999": 2214.014893999049,
          "99.9999": 2214.014893999049,
          "100.0": 2214.014893999049
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2201.959893234631,
            2179.8474884746734,
            2202.3414536561863,
            2209.874320959144,
            2214.014893999049
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day2Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2297.2426348482195,
        "scoreError": 57.899896268219,
        "scoreConfidence": [
          2239.3427385800005,
          2355.1425311164385
        ],
        "scorePercentiles": {
          "0.0": 2272.8691407776137,
          "50.0": 2304.82758030645,
          "90.0": 2309.7508174653904,
          "95.0": 2309.7508174653904,
          "99.0": 2309.7508174653904,
          "99.9": 2309.7508174653904,
          "99.99": 2309.7508174653904,
          "99.999": 2309.7508174653904,
          "99.9999": 2309.7508174653904,
          "100.0": 2309.7508174653904
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2272.8691407776137,
            2305.9843933671564,
            2309.7508174653904,
            2292.7812423244864,
            2304.82758030645
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day3Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1593.5835847911142,
        "scoreError": 19.621511332280807,
        "scoreConfidence": [
          1573.9620734588334,
          1613.205096123395
        ],
        "scorePercentiles": {
          "0.0": 1586.9984516251732,
          "50.0": 1592.8212374217098,
          "90.0": 1599.5946994938263,
          "95.0": 1599.5946994938263,
          "99.0": 1599.5946994938263,
          "99.9": 1599.5946994938263,
          "99.99": 1599.5946994938263,
          "99.999": 1599.5946994938263,
          "99.9999": 1599.5946994938263,
          "100.0": 1599.5946994938263
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1597.6348705298133,
            1592.8212374217098,
            1590.8686648850476,
            1586.9984516251732,
            1599.5946994938263
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day3Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1584.5750124179744,
        "scoreError": 29.03380091821668,
        "scoreConfidence": [
          1555.5412114997578,
          1613.6088133361911
        ],
        "scorePercentiles": {
          "0.0": 1572.5143100851585,
          "50.0": 1586.5143457475658,
          "90.0": 1593.1539189687915,
          "95.0": 1593.1539189687915,
          "99.0": 1593.1539189687915,
          "99.9": 1593.1539189687915,
          "99.99": 1593.1539189687915,
          "99.999": 1593.1539189687915,
          "99.9999": 1593.1539189687915,
          "100.0": 1593.1539189687915
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1586.6494631207622,
            1593.1539189687915,
            1572.5143100851585,
            1586.5143457475658,
            1584.0430241675945
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day4Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1050.933820304216,
        "scoreError": 24.47334343416352,
        "scoreConfidence": [
          1026.4604768700524,
          1075.4071637383795
        ],
        "scorePercentiles": {
          "0.0": 1040.3137830208748,
          "50.0": 1052.241056406692,
          "90.0": 1056.7780153236572,
          "95.0": 1056.7780153236572,
          "99.0": 1056.7780153236572,
          "99.9": 1056.7780153236572,
          "99.99": 1056.7780153236572,
          "99.999": 1056.7780153236572,
          "99.9999": 1056.7780153236572,
          "100.0": 1056.7780153236572
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1040.3137830208748,
            1050.8089786898088,
            1056.7780153236572,
            1054.527268080047,
            1052.241056406692
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day4Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1039.9585844347619,
        "scoreError": 15.618134402750199,
        "scoreConfidence": [
          1024.3404500320116,
          1055.576718837512
        ],
        "scorePercentiles": {
          "0.0": 1035.9370488207571,
          "50.0": 1038.6342927109993,
          "90.0": 1045.3843532920437,
          "95.0": 1045.3843532920437,
          "99.0": 1045.3843532920437,
          "99.9": 1045.3843532920437,
          "99.99": 1045.3843532920437,
          "99.999": 1045.3843532920437,
          "99.9999": 1045.3843532920437,
          "100.0": 1045.3843532920437
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1035.9370488207571,
            1042.954666354052,
            1038.6342927109993,
            1045.3843532920437,
            1036.8825609959576
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day5Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 5816.147474984221,
        "scoreError": 338.9820311030247,
        "scoreConfidence": [
          5477.165443881197,
          6155.129506087245
        ],
        "scorePercentiles": {
          "0.0": 5670.300528737676,
          "50.0": 5860.116060093495,
          "90.0": 5878.721954089737,
          "95.0": 5878.721954089737,
          "99.0": 5878.721954089737,
          "99.9": 5878.721954089737,
          "99.99": 5878.721954089737,
          "99.999": 5878.721954089737,
          "99.9999": 5878.721954089737,
          "100.0": 5878.721954089737
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            5796.388800990544,
            5860.116060093495,
            5670.300528737676,
            5878.721954089737,
            5875.21003100965
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day5Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 5112.939750652973,
        "scoreError": 210.14573420215163,
        "scoreConfidence": [
          4902.794016450822,
          5323.085484855124
        ],
        "scorePercentiles": {
          "0.0": 5017.207642431446,
          "50.0": 5135.01556616581,
          "90.0": 5150.565407866382,
          "95.0": 5150.565407866382,
          "99.0": 5150.565407866382,
          "99.9": 5150.565407866382,
          "99.99": 5150.565407866382,
          "99.999": 5150.565407866382,
          "99.9999": 5150.565407866382,
          "100.0": 5150.565407866382
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            5135.01556616581,
            5017.207642431446,
            5140.869522791938,
            5150.565407866382,
            5121.04061400929
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day6Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1230021.262985776,
        "scoreError": 6959.831734365814,
        "scoreConfidence": [
          1223061.4312514102,
          1236981.0947201417
        ],
        "scorePercentiles": {
          "0.0": 1226970.750107502,
          "50.0": 1230787.6506148821,
          "90.0": 1231605.4357088471,
          "95.0": 1231605.4357088471,
          "99.0": 1231605.4357088471,
          "99.9": 1231605.4357088471,
          "99.99": 1231605.4357088471,
          "99.999": 1231605.4357088471,
          "99.9999": 1231605.4357088471,
          "100.0": 1231605.4357088471
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1229913.0371906743,
            1230829.441306975,
            1230787.6506148821,
            1231605.4357088471,
            1226970.750107502
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day6Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4130725.3868988706,
        "scoreError": 61250.79951209063,
        "scoreConfidence": [
          4069474.58738678,
          4191976.186410961
        ],
        "scorePercentiles": {
          "0.0": 4113826.4235643162,
          "50.0": 4127821.3996923515,
          "90.0": 4152891.1050423626,
          "95.0": 4152891.1050423626,
          "99.0": 4152891.1050423626,
          "99.9": 4152891.1050423626,
          "99.99": 4152891.1050423626,
          "99.999": 4152891.1050423626,
          "99.9999": 4152891.1050423626,
          "100.0": 4152891.1050423626
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            4127821.3996923515,
            4113826.4235643162,
            4118961.799975368,
            4140126.2062199567,
            4152891.1050423626
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day7Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 185.95759775817456,
        "scoreError": 3.3307545411379267,
        "scoreConfidence": [
          182.62684321703662,
          189.2883522993125
        ],
        "scorePercentiles": {
          "0.0": 185.04814141312906,
          "50.0": 185.65622815987794,
          "90.0": 187.13253254903142,
          "95.0": 187.13253254903142,
          "99.0": 187.13253254903142,
          "99.9": 187.13253254903142,
          "99.99": 187.13253254903142,
          "99.999": 187.13253254903142,
          "99.9999": 187.13253254903142,
          "100.0": 187.13253254903142
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            185.04814141312906,
            186.56450657671712,
            185.65622815987794,
            187.13253254903142,
            185.38658009211719
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day7Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 181.47596411970272,
        "scoreError": 2.147512347361992,
        "scoreConfidence": [
          179.32845177234074,
          183.6234764670647
        ],
        "scorePercentiles": {
          "0.0": 180.76091512951663,
          "50.0": 181.34166573975668,
          "90.0": 182.22344984843772,
          "95.0": 182.22344984843772,
          "99.0": 182.22344984843772,
          "99.9": 182.22344984843772,
          "99.99": 182.22344984843772,
          "99.999": 182.22344984843772,
          "99.9999": 182.22344984843772,
          "100.0": 182.22344984843772
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            181.25223809168116,
            181.34166573975668,
            180.76091512951663,
            181.8015517891213,
            182.22344984843772
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day8Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1422.742606360707,
        "scoreError": 30.801025906464723,
        "scoreConfidence": [
          1391.9415804542423,
          1453.5436322671717
        ],
        "scorePercentiles": {
          "0.0": 1408.5319617315001,
          "50.0": 1426.2253699361504,
          "90.0": 1427.6480433555196,
          "95.0": 1427.6480433555196,
          "99.0": 1427.6480433555196,
          "99.9": 1427.6480433555196,
          "99.99": 1427.6480433555196,
          "99.999": 1427.6480433555196,
          "99.9999": 1427.6480433555196,
          "100.0": 1427.6480433555196
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1426.2253699361504,
            1426.3040720119677,
            1408.5319617315001,
            1427.6480433555196,
            1425.0035847683973
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day8Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 409.5050397311676,
        "scoreError": 3.120127460369112,
        "scoreConfidence": [
          406.38491227079845,
          412.6251671915367
        ],
        "scorePercentiles": {
          "0.0": 408.74299262481236,
          "50.0": 409.0745184001364,
          "90.0": 410.5373961985286,
          "95.0": 410.5373961985286,
          "99.0": 410.5373961985286,
          "99.9": 410.5373961985286,
          "99.99": 410.5373961985286,
          "99.999": 410.5373961985286,
          "99.9999": 410.5373961985286,
          "100.0": 410.5373961985286
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            408.74299262481236,
            409.0745184001364,
            408.9600044845956,
            410.2102869477648,
            410.5373961985286
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day9Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1113.9976161040195,
        "scoreError": 10.395849671491062,
        "scoreConfidence": [
          1103.6017664325284,
          1124.3934657755105
        ],
        "scorePercentiles": {
          "0.0": 1109.790926487359,
          "50.0": 1115.2398736916493,
          "90.0": 1116.6910618342883,
          "95.0": 1116.6910618342883,
          "99.0": 1116.6910618342883,
          "99.9": 1116.6910618342883,
          "99.99": 1116.6910618342883,
          "99.999": 1116.6910618342883,
          "99.9999": 1116.6910618342883,
          "100.0": 1116.6910618342883
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1115.2398736916493,
            1112.9876386867145,
            1116.6910618342883,
            1109.790926487359,
            1115.2785798200862
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day9Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 991.5467005892475,
        "scoreError": 26.896026291995913,
        "scoreConfidence": [
          964.6506742972516,
          1018.4427268812434
        ],
        "scorePercentiles": {
          "0.0": 982.604557673996,
          "50.0": 993.8025215009526,
          "90.0": 999.7743959086912,
          "95.0": 999.7743959086912,
          "99.0": 999.7743959086912,
          "99.9": 999.7743959086912,
          "99.99": 999.7743959086912,
          "99.999": 999.7743959086912,
          "99.9999": 999.7743959086912,
          "100.0": 999.7743959086912
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            995.3156667320757,
            982.604557673996,
            993.8025215009526,
            999.7743959086912,
            986.236361130522
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "linuxX64": [
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day1Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 423.75948903064364,
        "scoreError": 4.208491916070028,
        "scoreConfidence": [
          419.5509971145736,
          427.9679809467137
        ],
        "scorePercentiles": {
          "0.00": 416.1437235578052,
          "25.00": 419.5070019093587,
          "50.00": 424.2271950485444,
          "75.00": 427.7781231429783,
          "90.00": 428.4490596399082,
          "99.00": 428.4490596399082,
          "99.90": 428.4490596399082,
          "99.99": 428.4490596399082,
          "100.00": 428.4490596399082
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            427.1071866460484,
            416.1437235578052,
            428.4490596399082,
            424.2271950485444,
            422.87028026091224
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day1Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 312.7318643716837,
        "scoreError": 2.053237719073998,
        "scoreConfidence": [
          310.6786266526097,
          314.7851020907577
        ],
        "scorePercentiles": {
          "0.00": 310.21087056902763,
          "25.00": 310.33584101608955,
          "50.00": 313.60941903046904,
          "75.00": 314.68911039788526,
          "90.00": 315.6899230515751,
          "99.00": 315.6899230515751,
          "99.90": 315.6899230515751,
          "99.99": 315.6899230515751,
          "100.00": 315.6899230515751
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            313.60941903046904,
            315.6899230515751,
            313.68829774419544,
            310.21087056902763,
            310.46081146315146
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day2Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 452.57931012019947,
        "scoreError": 4.725742799051047,
        "scoreConfidence": [
          447.85356732114843,
          457.3050529192505
        ],
        "scorePercentiles": {
          "0.00": 444.7288168803408,
          "25.00": 447.09615753571234,
          "50.00": 454.4463682950867,
          "75.00": 457.128933617243,
          "90.00": 457.2786540042931,
          "99.00": 457.2786540042931,
          "99.90": 457.2786540042931,
          "99.99": 457.2786540042931,
          "100.00": 457.2786540042931
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            449.46349819108383,
            444.7288168803408,
            457.2786540042931,
            454.4463682950867,
            456.9792132301928
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day2Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 440.12365698173863,
        "scoreError": 3.225891125001763,
        "scoreConfidence": [
          436.8977658567369,
          443.3495481067404
        ],
        "scorePercentiles": {
          "0.00": 433.65346708080233,
          "25.00": 437.38920879357096,
          "50.00": 441.2856090783155,
          "75.00": 442.2771291216179,
          "90.00": 442.8629299006942,
          "99.00": 442.8629299006942,
          "99.90": 442.8629299006942,
          "99.99": 442.8629299006942,
          "100.00": 442.8629299006942
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            441.1249505063396,
            441.69132834254157,
            441.2856090783155,
            442.8629299006942,
            433.65346708080233
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day3Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 312.49395133721407,
        "scoreError": 3.496157658472878,
        "scoreConfidence": [
          308.9977936787412,
          315.99010899568697
        ],
        "scorePercentiles": {
          "0.00": 307.4136536812436,
          "25.00": 308.1879504490473,
          "50.00": 314.8723613161273,
          "75.00": 315.6107472359241,
          "90.00": 315.9764892207223,
          "99.00": 315.9764892207223,
          "99.90": 315.9764892207223,
          "99.99": 315.9764892207223,
          "100.00": 315.9764892207223
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            315.245005251126,
            308.96224721685104,
            315.9764892207223,
            307.4136536812436,
            314.8723613161273
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day3Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 328.89556711352964,
        "scoreError": 6.925572722785961,
        "scoreConfidence": [
          321.9699943907437,
          335.8211398363156
        ],
        "scorePercentiles": {
          "0.00": 323.8196263005163,
          "25.00": 323.9073519065823,
          "50.00": 326.7503835914149,
          "75.00": 334.95637408153425,
          "90.00": 342.7620644183297,
          "99.00": 342.7620644183297,
          "99.90": 342.7620644183297,
          "99.99": 342.7620644183297,
          "100.00": 342.7620644183297
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            342.7620644183297,
            323.99507751264827,
            323.8196263005163,
            327.15068374473884,
            326.7503835914149
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day4Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 184.05730176006085,
        "scoreError": 0.5982215165404291,
        "scoreConfidence": [
          183.45908024352042,
          184.6555232766013
        ],
        "scorePercentiles": {
          "0.00": 183.4224488161243,
          "25.00": 183.5894708085677,
          "50.00": 183.9200326037527,
          "75.00": 184.59376728970804,
          "90.00": 185.21632933877376,
          "99.00": 185.21632933877376,
          "99.90": 185.21632933877376,
          "99.99": 185.21632933877376,
          "100.00": 185.21632933877376
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            183.9200326037527,
            183.75649280101112,
            183.4224488161243,
            183.97120524064232,
            185.21632933877376
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day4Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 185.43564048439197,
        "scoreError": 1.826956763164796,
        "scoreConfidence": [
          183.60868372122718,
          187.26259724755676
        ],
        "scorePercentiles": {
          "0.00": 182.51678434652217,
          "25.00": 183.81198555293957,
          "50.00": 185.17655301534376,
          "75.00": 187.18883915036852,
          "90.00": 188.31463735151783,
          "99.00": 188.31463735151783,
          "99.90": 188.31463735151783,
          "99.99": 188.31463735151783,
          "100.00": 188.31463735151783
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            182.51678434652217,
            185.17655301534376,
            188.31463735151783,
            185.10718675935698,
            186.06304094921921
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day5Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 1442.3650157174436,
        "scoreError": 5.789609276985393,
        "scoreConfidence": [
          1436.5754064404582,
          1448.154624994429
        ],
        "scorePercentiles": {
          "0.00": 1437.561956473769,
          "25.00": 1438.2835827566898,
          "50.00": 1439.3878469419953,
          "75.00": 1447.9350330659213,
          "90.00": 1453.8187823604849,
          "99.00": 1453.8187823604849,
          "99.90": 1453.8187823604849,
          "99.99": 1453.8187823604849,
          "100.00": 1453.8187823604849
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            1453.8187823604849,
            1442.0512837713577,
            1439.3878469419953,
            1439.0052090396107,
            1437.561956473769
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day5Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 1209.1858997728073,
        "scoreError": 5.058627132681155,
        "scoreConfidence": [
          1204.1272726401262,
          1214.2445269054883
        ],
        "scorePercentiles": {
          "0.00": 1203.5983797923204,
          "25.00": 1204.928634662523,
          "50.00": 1207.883143462051,
          "75.00": 1214.0945430384695,
          "90.00": 1218.760897161717,
          "99.00": 1218.760897161717,
          "99.90": 1218.760897161717,
          "99.99": 1218.760897161717,
          "100.00": 1218.760897161717
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            1218.760897161717,
            1207.883143462051,
            1206.2588895327256,
            1203.5983797923204,
            1209.4281889152219
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day6Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 172282.56225966412,
        "scoreError": 1065.3476594772112,
        "scoreConfidence": [
          171217.2146001869,
          173347.90991914133
        ],
        "scorePercentiles": {
          "0.00": 170731.82623579275,
          "25.00": 171254.42548715475,
          "50.00": 172084.22792723987,
          "75.00": 173409.86619838563,
          "90.00": 173987.5781056812,
          "99.00": 173987.5781056812,
          "99.90": 173987.5781056812,
          "99.99": 173987.5781056812,
          "100.00": 173987.5781056812
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            172832.15429109006,
            171777.02473851677,
            172084.22792723987,
            170731.82623579275,
            173987.5781056812
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day6Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 1403894.0795743358,
        "scoreError": 15146.670143563299,
        "scoreConfidence": [
          1388747.4094307725,
          1419040.7497178991
        ],
        "scorePercentiles": {
          "0.00": 1373104.3959126978,
          "25.00": 1391326.7843029713,
          "50.00": 1411356.30189041,
          "75.00": 1412730.2636876632,
          "90.00": 1413866.226592039,
          "99.00": 1413866.226592039,
          "99.90": 1413866.226592039,
          "99.99": 1413866.226592039,
          "100.00": 1413866.226592039
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            1411594.3007832873,
            1413866.226592039,
            1411356.30189041,
            1409549.1726932449,
            1373104.3959126978
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day7Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 53.52336974418371,
        "scoreError": 1.1301577057207435,
        "scoreConfidence": [
          52.39321203846297,
          54.65352744990445
        ],
        "scorePercentiles": {
          "0.00": 51.77128297381681,
          "25.00": 52.16167248296708,
          "50.00": 54.1200650938103,
          "75.00": 54.58671933058706,
          "90.00": 54.68390419310719,
          "99.00": 54.68390419310719,
          "99.90": 54.68390419310719,
          "99.99": 54.68390419310719,
          "100.00": 54.68390419310719
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            51.77128297381681,
            52.552061992117345,
            54.68390419310719,
            54.1200650938103,
            54.48953446806692
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day7Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 55.56752827707767,
        "scoreError": 0.613276343780208,
        "scoreConfidence": [
          54.95425193329746,
          56.18080462085788
        ],
        "scorePercentiles": {
          "0.00": 54.42705262750572,
          "25.00": 54.931446445565825,
          "50.00": 55.73673217173558,
          "75.00": 56.11900816126057,
          "90.00": 56.15877489632564,
          "99.00": 56.15877489632564,
          "99.90": 56.15877489632564,
          "99.99": 56.15877489632564,
          "100.00": 56.15877489632564
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            56.079241426195495,
            55.73673217173558,
            56.15877489632564,
            55.435840263625934,
            54.42705262750572
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day8Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 224.12291662580554,
        "scoreError": 2.9892933830832074,
        "scoreConfidence": [
          221.13362324272234,
          227.11221000888875
        ],
        "scorePercentiles": {
          "0.00": 219.27150552617374,
          "25.00": 220.94466445514138,
          "50.00": 224.12602553274513,
          "75.00": 227.29961434299992,
          "90.00": 227.81793349476004,
          "99.00": 227.81793349476004,
          "99.90": 227.81793349476004,
          "99.99": 227.81793349476004,
          "100.00": 227.81793349476004
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            219.27150552617374,
            224.12602553274513,
            226.78129519123976,
            227.81793349476004,
            222.617823384109
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day8Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 152.8737169724529,
        "scoreError": 0.670145255152053,
        "scoreConfidence": [
          152.20357171730086,
          153.54386222760496
        ],
        "scorePercentiles": {
          "0.00": 151.99663464747948,
          "25.00": 152.07498724848676,
          "50.00": 153.1826050006736,
          "75.00": 153.51800268230875,
          "90.00": 153.76722541539073,
          "99.00": 153.76722541539073,
          "99.90": 153.76722541539073,
          "99.99": 153.76722541539073,
          "100.00": 153.76722541539073
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            152.15333984949402,
            153.76722541539073,
            153.1826050006736,
            153.26877994922674,
            151.99663464747948
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day9Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 307.2687194053909,
        "scoreError": 1.98777450300983,
        "scoreConfidence": [
          305.2809449023811,
          309.2564939084007
        ],
        "scorePercentiles": {
          "0.00": 304.0392165373245,
          "25.00": 305.0245719085725,
          "50.00": 307.77536272544774,
          "75.00": 309.25954524218093,
          "90.00": 309.6914791943011,
          "99.00": 309.6914791943011,
          "99.90": 309.6914791943011,
          "99.99": 309.6914791943011,
          "100.00": 309.6914791943011
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            308.8276112900608,
            306.00992727982054,
            307.77536272544774,
            309.6914791943011,
            304.0392165373245
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2023.exe.Day9Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 286.02255639374323,
        "scoreError": 4.176423390262483,
        "scoreConfidence": [
          281.84613300348076,
          290.1989797840057
        ],
        "scorePercentiles": {
          "0.00": 282.4043992047549,
          "25.00": 282.9410572541731,
          "50.00": 283.6393310263963,
          "75.00": 290.29566821698677,
          "90.00": 294.1063486958051,
          "99.00": 294.1063486958051,
          "99.90": 294.1063486958051,
          "99.99": 294.1063486958051,
          "100.00": 294.1063486958051
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            286.4849877381685,
            282.4043992047549,
            283.6393310263963,
            283.4777153035912,
            294.1063486958051
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ]
};
