// provided.js - generated by ephemient/aoc2023/Kotlin benchmarks, 2023-12-07 07:12:18.674588454

var providedBenchmarks = ["jvmTest"];

var providedBenchmarkStore = {
  "jvmTest": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day1Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1547.0818390597565,
        "scoreError": 32.41507385127861,
        "scoreConfidence": [
          1514.666765208478,
          1579.496912911035
        ],
        "scorePercentiles": {
          "0.0": 1537.5173917409413,
          "50.0": 1544.0121677107295,
          "90.0": 1556.3355972208751,
          "95.0": 1556.3355972208751,
          "99.0": 1556.3355972208751,
          "99.9": 1556.3355972208751,
          "99.99": 1556.3355972208751,
          "99.999": 1556.3355972208751,
          "99.9999": 1556.3355972208751,
          "100.0": 1556.3355972208751
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1544.0121677107295,
            1542.0188689063941,
            1556.3355972208751,
            1555.5251697198423,
            1537.5173917409413
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day1Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1107.746829505249,
        "scoreError": 16.85023291594977,
        "scoreConfidence": [
          1090.8965965892992,
          1124.5970624211989
        ],
        "scorePercentiles": {
          "0.0": 1100.4318184409117,
          "50.0": 1109.9097223608082,
          "90.0": 1111.246525214236,
          "95.0": 1111.246525214236,
          "99.0": 1111.246525214236,
          "99.9": 1111.246525214236,
          "99.99": 1111.246525214236,
          "99.999": 1111.246525214236,
          "99.9999": 1111.246525214236,
          "100.0": 1111.246525214236
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1100.4318184409117,
            1111.246525214236,
            1109.9097223608082,
            1107.0246205332912,
            1110.1214609769975
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day2Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2269.2399720405924,
        "scoreError": 105.1439461008731,
        "scoreConfidence": [
          2164.0960259397193,
          2374.3839181414655
        ],
        "scorePercentiles": {
          "0.0": 2224.552526810127,
          "50.0": 2281.7762993430965,
          "90.0": 2289.4399619711635,
          "95.0": 2289.4399619711635,
          "99.0": 2289.4399619711635,
          "99.9": 2289.4399619711635,
          "99.99": 2289.4399619711635,
          "99.999": 2289.4399619711635,
          "99.9999": 2289.4399619711635,
          "100.0": 2289.4399619711635
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2281.7762993430965,
            2262.009658241477,
            2289.4399619711635,
            2288.4214138370967,
            2224.552526810127
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day2Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2275.2080401565477,
        "scoreError": 167.11375234956307,
        "scoreConfidence": [
          2108.0942878069845,
          2442.321792506111
        ],
        "scorePercentiles": {
          "0.0": 2198.3895201658893,
          "50.0": 2289.953804834862,
          "90.0": 2304.093675536353,
          "95.0": 2304.093675536353,
          "99.0": 2304.093675536353,
          "99.9": 2304.093675536353,
          "99.99": 2304.093675536353,
          "99.999": 2304.093675536353,
          "99.9999": 2304.093675536353,
          "100.0": 2304.093675536353
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2287.911430044876,
            2198.3895201658893,
            2304.093675536353,
            2295.691770200758,
            2289.953804834862
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day3Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1593.1693201065266,
        "scoreError": 44.11804915206085,
        "scoreConfidence": [
          1549.0512709544657,
          1637.2873692585874
        ],
        "scorePercentiles": {
          "0.0": 1573.922005079501,
          "50.0": 1595.512468827975,
          "90.0": 1603.482737314218,
          "95.0": 1603.482737314218,
          "99.0": 1603.482737314218,
          "99.9": 1603.482737314218,
          "99.99": 1603.482737314218,
          "99.999": 1603.482737314218,
          "99.9999": 1603.482737314218,
          "100.0": 1603.482737314218
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1595.512468827975,
            1573.922005079501,
            1599.7085682924455,
            1593.2208210184936,
            1603.482737314218
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day3Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1612.2759302013378,
        "scoreError": 48.65419298440312,
        "scoreConfidence": [
          1563.6217372169347,
          1660.930123185741
        ],
        "scorePercentiles": {
          "0.0": 1589.8670337240287,
          "50.0": 1616.8961757018756,
          "90.0": 1620.5221274708745,
          "95.0": 1620.5221274708745,
          "99.0": 1620.5221274708745,
          "99.9": 1620.5221274708745,
          "99.99": 1620.5221274708745,
          "99.999": 1620.5221274708745,
          "99.9999": 1620.5221274708745,
          "100.0": 1620.5221274708745
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1617.9339821295903,
            1620.5221274708745,
            1616.1603319803212,
            1589.8670337240287,
            1616.8961757018756
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day4Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1055.7837860471293,
        "scoreError": 23.531321512491196,
        "scoreConfidence": [
          1032.2524645346382,
          1079.3151075596204
        ],
        "scorePercentiles": {
          "0.0": 1046.7227689895462,
          "50.0": 1057.4716934867643,
          "90.0": 1062.6985931742095,
          "95.0": 1062.6985931742095,
          "99.0": 1062.6985931742095,
          "99.9": 1062.6985931742095,
          "99.99": 1062.6985931742095,
          "99.999": 1062.6985931742095,
          "99.9999": 1062.6985931742095,
          "100.0": 1062.6985931742095
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1058.885837145498,
            1057.4716934867643,
            1053.140037439628,
            1062.6985931742095,
            1046.7227689895462
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day4Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1037.68976552082,
        "scoreError": 22.05741888673803,
        "scoreConfidence": [
          1015.632346634082,
          1059.747184407558
        ],
        "scorePercentiles": {
          "0.0": 1032.2607567816383,
          "50.0": 1035.7429679535867,
          "90.0": 1046.9711194944794,
          "95.0": 1046.9711194944794,
          "99.0": 1046.9711194944794,
          "99.9": 1046.9711194944794,
          "99.99": 1046.9711194944794,
          "99.999": 1046.9711194944794,
          "99.9999": 1046.9711194944794,
          "100.0": 1046.9711194944794
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1035.7429679535867,
            1038.9761617209554,
            1032.2607567816383,
            1034.4978216534391,
            1046.9711194944794
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day5Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 5834.933493866457,
        "scoreError": 132.29994955333828,
        "scoreConfidence": [
          5702.633544313118,
          5967.233443419796
        ],
        "scorePercentiles": {
          "0.0": 5787.603115687204,
          "50.0": 5838.604199925549,
          "90.0": 5872.468131453102,
          "95.0": 5872.468131453102,
          "99.0": 5872.468131453102,
          "99.9": 5872.468131453102,
          "99.99": 5872.468131453102,
          "99.999": 5872.468131453102,
          "99.9999": 5872.468131453102,
          "100.0": 5872.468131453102
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            5787.603115687204,
            5860.806194803762,
            5872.468131453102,
            5815.185827462668,
            5838.604199925549
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day5Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 5112.905861219502,
        "scoreError": 60.53964721172774,
        "scoreConfidence": [
          5052.366214007774,
          5173.44550843123
        ],
        "scorePercentiles": {
          "0.0": 5087.1158338325,
          "50.0": 5116.973724398913,
          "90.0": 5128.607060065272,
          "95.0": 5128.607060065272,
          "99.0": 5128.607060065272,
          "99.9": 5128.607060065272,
          "99.99": 5128.607060065272,
          "99.999": 5128.607060065272,
          "99.9999": 5128.607060065272,
          "100.0": 5128.607060065272
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            5087.1158338325,
            5111.312395272879,
            5120.520292527946,
            5116.973724398913,
            5128.607060065272
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day6Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1279994.2568862997,
        "scoreError": 6865.921605770449,
        "scoreConfidence": [
          1273128.3352805292,
          1286860.1784920702
        ],
        "scorePercentiles": {
          "0.0": 1276915.0417435651,
          "50.0": 1280566.0039466587,
          "90.0": 1281548.2841439538,
          "95.0": 1281548.2841439538,
          "99.0": 1281548.2841439538,
          "99.9": 1281548.2841439538,
          "99.99": 1281548.2841439538,
          "99.999": 1281548.2841439538,
          "99.9999": 1281548.2841439538,
          "100.0": 1281548.2841439538
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1280566.0039466587,
            1281548.2841439538,
            1276915.0417435651,
            1280610.9734437983,
            1280330.9811535215
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day6Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4125633.3495318964,
        "scoreError": 54086.392731271524,
        "scoreConfidence": [
          4071546.9568006247,
          4179719.742263168
        ],
        "scorePercentiles": {
          "0.0": 4107264.8398204306,
          "50.0": 4124212.15031792,
          "90.0": 4146713.4774485594,
          "95.0": 4146713.4774485594,
          "99.0": 4146713.4774485594,
          "99.9": 4146713.4774485594,
          "99.99": 4146713.4774485594,
          "99.999": 4146713.4774485594,
          "99.9999": 4146713.4774485594,
          "100.0": 4146713.4774485594
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            4107264.8398204306,
            4124212.15031792,
            4123481.2617238103,
            4146713.4774485594,
            4126495.01834876
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day7Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 212.38950518601374,
        "scoreError": 5.02512636485434,
        "scoreConfidence": [
          207.3643788211594,
          217.41463155086808
        ],
        "scorePercentiles": {
          "0.0": 211.40286786557814,
          "50.0": 211.65394114983332,
          "90.0": 214.39849601469393,
          "95.0": 214.39849601469393,
          "99.0": 214.39849601469393,
          "99.9": 214.39849601469393,
          "99.99": 214.39849601469393,
          "99.999": 214.39849601469393,
          "99.9999": 214.39849601469393,
          "100.0": 214.39849601469393
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            213.0273024252153,
            211.65394114983332,
            214.39849601469393,
            211.46491847474792,
            211.40286786557814
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day7Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 209.92203473059004,
        "scoreError": 3.6537862977569326,
        "scoreConfidence": [
          206.2682484328331,
          213.57582102834698
        ],
        "scorePercentiles": {
          "0.0": 208.7857031893892,
          "50.0": 209.84552410603905,
          "90.0": 211.30469808745866,
          "95.0": 211.30469808745866,
          "99.0": 211.30469808745866,
          "99.9": 211.30469808745866,
          "99.99": 211.30469808745866,
          "99.999": 211.30469808745866,
          "99.9999": 211.30469808745866,
          "100.0": 211.30469808745866
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            208.7857031893892,
            210.27197303477,
            209.4022752352933,
            211.30469808745866,
            209.84552410603905
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ]
};
