// provided.js - generated by ephemient/aoc2023/Kotlin benchmarks, 2023-12-02 00:55:04.839983223

var providedBenchmarks = ["jvmTest"];

var providedBenchmarkStore = {
  "jvmTest": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day1Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1545.9682072155142,
        "scoreError": 26.841388216169634,
        "scoreConfidence": [
          1519.1268189993446,
          1572.8095954316839
        ],
        "scorePercentiles": {
          "0.0": 1537.9981495433856,
          "50.0": 1547.676578929948,
          "90.0": 1552.6943241737886,
          "95.0": 1552.6943241737886,
          "99.0": 1552.6943241737886,
          "99.9": 1552.6943241737886,
          "99.99": 1552.6943241737886,
          "99.999": 1552.6943241737886,
          "99.9999": 1552.6943241737886,
          "100.0": 1552.6943241737886
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1539.3106705134626,
            1552.6943241737886,
            1537.9981495433856,
            1547.676578929948,
            1552.161312916985
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2023.exe.Day1Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.9",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.9+9",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1103.3978626764758,
        "scoreError": 26.42572397075781,
        "scoreConfidence": [
          1076.972138705718,
          1129.8235866472337
        ],
        "scorePercentiles": {
          "0.0": 1094.9587369445564,
          "50.0": 1101.8602379735605,
          "90.0": 1112.0635557451053,
          "95.0": 1112.0635557451053,
          "99.0": 1112.0635557451053,
          "99.9": 1112.0635557451053,
          "99.99": 1112.0635557451053,
          "99.999": 1112.0635557451053,
          "99.9999": 1112.0635557451053,
          "100.0": 1112.0635557451053
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1099.6460953988874,
            1101.8602379735605,
            1108.46068732027,
            1094.9587369445564,
            1112.0635557451053
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ]
};
