name: Kotlin CI

on:
  push:
    branches: [ main ]
    paths: [ kt/** ]
  pull_request:
    branches: [ main ]
    paths: [ kt/** ]

  workflow_dispatch:

jobs:
  get-inputs:
    uses: ephemient/aoc2023/.github/workflows/get-inputs.yml@main
    secrets:
      SESSION: ${{ secrets.SESSION }}

  gradle-wrapper-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build distZip
          build-root-directory: kt
      - uses: actions/upload-artifact@v3
        with:
          name: aoc2023-exe
          path: kt/aoc2023-exe/build/distributions/*.zip
      - uses: actions/upload-artifact@v3
        with:
          name: aoc2023-kexe
          path: |
            kt/aoc2023-exe/build/bin/*/debugExecutable/*.kexe
            kt/aoc2023-exe/build/bin/*/releaseExecutable/*.kexe

  run-jvm:
    needs: [ get-inputs, build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: inputs
          path: inputs
      - uses: actions/download-artifact@v3
        with:
          name: aoc2023-exe
      - run: unzip aoc2023-exe.zip
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: aoc2023-exe/bin/aoc2023-exe
        env:
          AOC2023_DATADIR: inputs

  run-native:
    needs: [ get-inputs, build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: inputs
          path: inputs
      - uses: actions/download-artifact@v3
        with:
          name: aoc2023-kexe
      - run: chmod +x linuxX64/*/aoc2023-exe.kexe
      - run: linuxX64/releaseExecutable/aoc2023-exe.kexe
        env:
          AOC2023_DATADIR: inputs
